spring.application.name=gate-api
server.port=8080
server.servlet.context-path=/api

# MongoDB Atlas — substitua <db_password> pela senha real
spring.data.mongodb.uri=mongodb+srv://pedrojuchimiuk_db_user:<db_password>@cruster0.ddnfbzt.mongodb.net/gate_data?retryWrites=true&w=majority
spring.data.mongodb.database=gate_data
